# Generated by Django 4.0 on 2021-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='quest_can_pause',
        ),
        migrations.AddField(
            model_name='room',
            name='gfb_zeta_jones_11uest_can_pause',
            field=models.BooleanField(default=False),
        ),
    ]
