# Generated by Django 4.0 on 2021-12-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_room_quest_can_pause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='gfb_zeta_jones_11uest_can_pause',
            new_name='guest_can_pause',
        ),
    ]
